### ISSUE TITLE
Selftest running into multiple issues

### ISSUE THREAD

**Issue by rgarcia89** [respawner/peering-manager#149]
### Environment
* Python version: 3.7.3
* Peering Manager version:  Every release after 26. June

### Steps to Reproduce
Pull the latest version and run the Django selftest

```$ cd /opt/peering-manager/ && python3 manage.py test
Creating test database for alias 'default'...
.........................................................................................................................................................................................
----------------------------------------------------------------------
Ran 185 tests in 113.400s

OK
Destroying test database for alias 'default'...
System check identified no issues (0 silenced).```

<!-- What happened instead? -->
```$ cd /opt/peering-manager/ && python3 manage.py test
Creating test database for alias 'default'...
......E......E.......E......E......E......E.........E...........E.........................E.....................................................................................................
======================================================================
ERROR: test_get_irr_as_set_prefixes (peering.tests.test_api.AutonomousSystemTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/peering-manager/peering/tests/test_api.py", line 116, in test_get_irr_as_set_prefixes
    response = self.client.get(url, format="json", **self.header)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/test.py", line 292, in get
    response = super(APIClient, self).get(path, data=data, **extra)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/test.py", line 209, in get
    return self.generic('GET', path, **r)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/test.py", line 238, in generic
    method, path, data, content_type, secure, **extra)
  File "/usr/local/lib/python3.7/site-packages/django/test/client.py", line 422, in generic
    return self.request(**r)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/test.py", line 289, in request
    return super(APIClient, self).request(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/test.py", line 241, in request
    request = super(APIRequestFactory, self).request(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/test/client.py", line 503, in request
    raise exc_value
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/viewsets.py", line 116, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/peering-manager/peering/api/views.py", line 79, in get_irr_as_set_prefixes
    return Response({"prefixes": self.get_object().get_irr_as_set_prefixes()})
  File "/opt/peering-manager/peering/models.py", line 260, in get_irr_as_set_prefixes
    prefixes["ipv6"].extend(call_irr_as_set_resolver(as_set, ip_version=6))
  File "/opt/peering-manager/peering/__init__.py", line 46, in call_irr_as_set_resolver
    raise ValueError(error_log)
ValueError: bgpq3 exit code is 1, stderr: b"ERROR:Invalid source(s) 'RIPE,APNIC,AFRINIC,ARIN,NTTCOM,ALTDB,BBOI,BELL,JPIRR,LEVEL3,RADB,RGNET,SAVVIS,TC': F One or more selected sources are unavailable.\n\n"

======================================================================
ERROR: test_delete_bgp_group (peering.tests.test_api.BGPGroupTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
psycopg2.errors.ForeignKeyViolation: insert or update on table "utils_objectchange" violates foreign key constraint "utils_objectchange_user_id_0e6d8ab5_fk_auth_user_id"
DETAIL:  Key (user_id)=(7) is not present in table "auth_user".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/test/testcases.py", line 274, in __call__
    self._post_teardown()
  File "/usr/local/lib/python3.7/site-packages/django/test/testcases.py", line 1009, in _post_teardown
    self._fixture_teardown()
  File "/usr/local/lib/python3.7/site-packages/django/test/testcases.py", line 1177, in _fixture_teardown
    connections[db_name].check_constraints()
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 246, in check_constraints
    self.cursor().execute('SET CONSTRAINTS ALL IMMEDIATE')
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
django.db.utils.IntegrityError: insert or update on table "utils_objectchange" violates foreign key constraint "utils_objectchange_user_id_0e6d8ab5_fk_auth_user_id"
DETAIL:  Key (user_id)=(7) is not present in table "auth_user".


======================================================================
ERROR: test_delete_community (peering.tests.test_api.CommunityTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
psycopg2.errors.ForeignKeyViolation: insert or update on table "utils_objectchange" violates foreign key constraint "utils_objectchange_user_id_0e6d8ab5_fk_auth_user_id"
DETAIL:  Key (user_id)=(7) is not present in table "auth_user".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/test/testcases.py", line 274, in __call__
    self._post_teardown()
  File "/usr/local/lib/python3.7/site-packages/django/test/testcases.py", line 1009, in _post_teardown
    self._fixture_teardown()
  File "/usr/local/lib/python3.7/site-packages/django/test/testcases.py", line 1177, in _fixture_teardown
    connections[db_name].check_constraints()
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 246, in check_constraints
    self.cursor().execute('SET CONSTRAINTS ALL IMMEDIATE')
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
django.db.utils.IntegrityError: insert or update on table "utils_objectchange" violates foreign key constraint "utils_objectchange_user_id_0e6d8ab5_fk_auth_user_id"
DETAIL:  Key (user_id)=(7) is not present in table "auth_user".


======================================================================
ERROR: test_delete_configuration_template (peering.tests.test_api.ConfigurationTemplateTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
psycopg2.errors.ForeignKeyViolation: insert or update on table "utils_objectchange" violates foreign key constraint "utils_objectchange_user_id_0e6d8ab5_fk_auth_user_id"
DETAIL:  Key (user_id)=(7) is not present in table "auth_user".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/test/testcases.py", line 274, in __call__
    self._post_teardown()
  File "/usr/local/lib/python3.7/site-packages/django/test/testcases.py", line 1009, in _post_teardown
    self._fixture_teardown()
  File "/usr/local/lib/python3.7/site-packages/django/test/testcases.py", line 1177, in _fixture_teardown
    connections[db_name].check_constraints()
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 246, in check_constraints
    self.cursor().execute('SET CONSTRAINTS ALL IMMEDIATE')
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
django.db.utils.IntegrityError: insert or update on table "utils_objectchange" violates foreign key constraint "utils_objectchange_user_id_0e6d8ab5_fk_auth_user_id"
DETAIL:  Key (user_id)=(7) is not present in table "auth_user".


======================================================================
ERROR: test_delete_direct_peering_session (peering.tests.test_api.DirectPeeringSessionTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
psycopg2.errors.ForeignKeyViolation: insert or update on table "utils_objectchange" violates foreign key constraint "utils_objectchange_user_id_0e6d8ab5_fk_auth_user_id"
DETAIL:  Key (user_id)=(7) is not present in table "auth_user".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/test/testcases.py", line 274, in __call__
    self._post_teardown()
  File "/usr/local/lib/python3.7/site-packages/django/test/testcases.py", line 1009, in _post_teardown
    self._fixture_teardown()
  File "/usr/local/lib/python3.7/site-packages/django/test/testcases.py", line 1177, in _fixture_teardown
    connections[db_name].check_constraints()
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 246, in check_constraints
    self.cursor().execute('SET CONSTRAINTS ALL IMMEDIATE')
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
django.db.utils.IntegrityError: insert or update on table "utils_objectchange" violates foreign key constraint "utils_objectchange_user_id_0e6d8ab5_fk_auth_user_id"
DETAIL:  Key (user_id)=(7) is not present in table "auth_user".


======================================================================
ERROR: test_delete_internet_exchange_peering_session (peering.tests.test_api.InternetExchangePeeringSessionTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
psycopg2.errors.ForeignKeyViolation: insert or update on table "utils_objectchange" violates foreign key constraint "utils_objectchange_user_id_0e6d8ab5_fk_auth_user_id"
DETAIL:  Key (user_id)=(7) is not present in table "auth_user".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/test/testcases.py", line 274, in __call__
    self._post_teardown()
  File "/usr/local/lib/python3.7/site-packages/django/test/testcases.py", line 1009, in _post_teardown
    self._fixture_teardown()
  File "/usr/local/lib/python3.7/site-packages/django/test/testcases.py", line 1177, in _fixture_teardown
    connections[db_name].check_constraints()
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 246, in check_constraints
    self.cursor().execute('SET CONSTRAINTS ALL IMMEDIATE')
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
django.db.utils.IntegrityError: insert or update on table "utils_objectchange" violates foreign key constraint "utils_objectchange_user_id_0e6d8ab5_fk_auth_user_id"
DETAIL:  Key (user_id)=(7) is not present in table "auth_user".


======================================================================
ERROR: test_delete_internet_exchange (peering.tests.test_api.InternetExchangeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
psycopg2.errors.ForeignKeyViolation: insert or update on table "utils_objectchange" violates foreign key constraint "utils_objectchange_user_id_0e6d8ab5_fk_auth_user_id"
DETAIL:  Key (user_id)=(7) is not present in table "auth_user".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/test/testcases.py", line 274, in __call__
    self._post_teardown()
  File "/usr/local/lib/python3.7/site-packages/django/test/testcases.py", line 1009, in _post_teardown
    self._fixture_teardown()
  File "/usr/local/lib/python3.7/site-packages/django/test/testcases.py", line 1177, in _fixture_teardown
    connections[db_name].check_constraints()
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 246, in check_constraints
    self.cursor().execute('SET CONSTRAINTS ALL IMMEDIATE')
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
django.db.utils.IntegrityError: insert or update on table "utils_objectchange" violates foreign key constraint "utils_objectchange_user_id_0e6d8ab5_fk_auth_user_id"
DETAIL:  Key (user_id)=(7) is not present in table "auth_user".


======================================================================
ERROR: test_delete_router (peering.tests.test_api.RouterTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
psycopg2.errors.ForeignKeyViolation: insert or update on table "utils_objectchange" violates foreign key constraint "utils_objectchange_user_id_0e6d8ab5_fk_auth_user_id"
DETAIL:  Key (user_id)=(7) is not present in table "auth_user".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/test/testcases.py", line 274, in __call__
    self._post_teardown()
  File "/usr/local/lib/python3.7/site-packages/django/test/testcases.py", line 1009, in _post_teardown
    self._fixture_teardown()
  File "/usr/local/lib/python3.7/site-packages/django/test/testcases.py", line 1177, in _fixture_teardown
    connections[db_name].check_constraints()
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 246, in check_constraints
    self.cursor().execute('SET CONSTRAINTS ALL IMMEDIATE')
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
django.db.utils.IntegrityError: insert or update on table "utils_objectchange" violates foreign key constraint "utils_objectchange_user_id_0e6d8ab5_fk_auth_user_id"
DETAIL:  Key (user_id)=(7) is not present in table "auth_user".


======================================================================
ERROR: test_get_irr_as_set_prefixes (peering.tests.test_models.AutonomousSystemTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/peering-manager/peering/tests/test_models.py", line 83, in test_get_irr_as_set_prefixes
    prefixes = autonomous_system.get_irr_as_set_prefixes()
  File "/opt/peering-manager/peering/models.py", line 260, in get_irr_as_set_prefixes
    prefixes["ipv6"].extend(call_irr_as_set_resolver(as_set, ip_version=6))
  File "/opt/peering-manager/peering/__init__.py", line 46, in call_irr_as_set_resolver
    raise ValueError(error_log)
ValueError: bgpq3 exit code is 1, stderr: b"ERROR:Invalid source(s) 'RIPE,APNIC,AFRINIC,ARIN,NTTCOM,ALTDB,BBOI,BELL,JPIRR,LEVEL3,RADB,RGNET,SAVVIS,TC': F One or more selected sources are unavailable.\n\n"

----------------------------------------------------------------------
Ran 185 tests in 51.683s

FAILED (errors=9)
Destroying test database for alias 'default'...
System check identified no issues (0 silenced).```

**Comment by respawner** [comment]
I can reproduce the issue with bgpq3 failing due to invalid source(s). However I do not have the other failures that look like errors due to user (with ID 7) missing from the users table. What's weird is that the failures seem to only appear for tests ensuring the proper deletion of objects. Did you do anything special about the users recently?

**Comment by rgarcia89** [comment]
Not that I would be aware of. The database as well as the container that runs the tests are build during runtime and destroyed afterwards. So it is always a totally new deployment. Is there a quick fix that I can implemented in regards of the invalid sources? I will check back on it tomorrow once I am back at work.

**Comment by rgarcia89** [comment]
Self test is completing successful again.
Thanks for the quick fix :)
