### ISSUE TITLE
Issue with IOS module after napalm-ansible 0.9.0 upgrade

### ISSUE THREAD

**Issue by Joevilla** [respawner/peering-manager#15]
After upgrading to the new napalm-ansible 0.9.0. Any play I run for ios fails with the below. EOS and NXOS are fine. It was installed via the setup command sudo python ./setup.py install

FAILED! => {"changed": false, "failed": true, "msg": "cannot connect to device: Cannot import \"napalm_ios\". Is the library installed?"}

sudo pip freeze | grep napalm
napalm==2.3.0
napalm-ansible==0.9.0
napalm-base==0.25.0
napalm-eos==0.5.2
napalm-fortios==0.3.1
napalm-ibm==0.1.6
napalm-ios==0.8.1
napalm-iosxr==0.4.6
napalm-junos==0.6.2
napalm-nxos==0.7.0
napalm-panos==0.3.0
napalm-pluribus==0.5.0
napalm-ros==0.2.0
napalm-vyos==0.1.2
napalm-yang==0.0.7

jvill@mgt1:~/ansible> python -c "from napalm.ios import IOSDriver"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/ixea/lib/python2.7/site-packages/napalm/ios/__init__.py", line 16, in <module>
    from napalm.ios.ios import IOSDriver
  File "/opt/ixea/lib/python2.7/site-packages/napalm/ios/ios.py", line 28, in <module>
    from netmiko import ConnectHandler, FileTransfer, InLineTransfer
  File "/opt/ixea/lib/python2.7/site-packages/netmiko/__init__.py", line 8, in <module>
    from netmiko.ssh_dispatcher import ConnectHandler
  File "/opt/ixea/lib/python2.7/site-packages/netmiko/ssh_dispatcher.py", line 4, in <module>
    from netmiko.a10 import A10SSH
  File "/opt/ixea/lib/python2.7/site-packages/netmiko/a10/__init__.py", line 2, in <module>
    from netmiko.a10.a10_ssh import A10SSH
  File "/opt/ixea/lib/python2.7/site-packages/netmiko/a10/a10_ssh.py", line 4, in <module>
    from netmiko.cisco_base_connection import CiscoSSHConnection
  File "/opt/ixea/lib/python2.7/site-packages/netmiko/cisco_base_connection.py", line 3, in <module>
    from netmiko.base_connection import BaseConnection
  File "/opt/ixea/lib/python2.7/site-packages/netmiko/base_connection.py", line 24, in <module>
    from netmiko.utilities import write_bytes, check_serial_port, get_structured_data
  File "/opt/ixea/lib/python2.7/site-packages/netmiko/utilities.py", line 8, in <module>
    import serial.tools.list_ports

>>> napalm.get_network_driver('ios')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/jons/lib/python2.7/site-packages/napalm/base/__init__.py", line 95, in get_network_driver
    install_name=module_install_name
napalm.base.exceptions.ModuleImportError: Cannot import "napalm.ios". Is the library installed?

**Comment by respawner** [comment]
Seems like an issue of NAPALM or its Ansible related project.

I suggest you to go to the napalm-ansible issue tracker rather than here.
