### ISSUE TITLE
Peeringdb_sync command error

### ISSUE THREAD

**Issue by jjavierweb** [respawner/peering-manager#235]
### Environment
* Python version:  3.6.9
* Peering Manager version: 1.1.1-dev

### Steps to Reproduce
python3 manage.py peeringdb_sync

### Expected Behavior
PeeringDB to sync to the database

### Observed Behavior
A database issue with UTF8 and LATTIN1

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UntranslatableCharacter: character with byte sequence 0xef 0xbf 0xbd in encoding "UTF8" has no equivalent in encoding "LATIN1"

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/opt/peering-manager/peeringdb/management/commands/peeringdb_sync.py", line 17, in handle
    api.update_local_database(api.get_last_sync_time())
  File "/opt/peering-manager/peeringdb/http.py", line 252, in update_local_database
    changes = self.synchronize_objects(last_sync, namespace, object_type)
  File "/opt/peering-manager/peeringdb/http.py", line 212, in synchronize_objects
    local_object.save()
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/base.py", line 779, in save_base
    force_update, using, update_fields,
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/base.py", line 851, in _save_table
    forced_update)
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/base.py", line 900, in _do_update
    return filtered._update(values) > 0
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/query.py", line 760, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/sql/compiler.py", line 1469, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/sql/compiler.py", line 1140, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/dist-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.6/dist-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.6/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/dist-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.6/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.DataError: character with byte sequence 0xef 0xbf 0xbd in encoding "UTF8" has no equivalent in encoding "LATIN1"

**Comment by mngan** [comment]
I had this problem too and I had to re-create the database using these parameters. You can't change the existing database, so you have to dump, drop and restore the database. You should use the appropriate collation type for your locale. 

```
CREATE DATABASE "peering_manager"
    WITH OWNER "postgres"
    ENCODING 'UTF8'
    LC_COLLATE = 'en_US.UTF-8'
    LC_CTYPE = 'en_US.UTF-8'
    TEMPLATE template0;
```

**Comment by respawner** [comment]
I guess there an easy fix to do, by just modifying the [documentation about PostgreSQL](https://github.com/respawner/peering-manager/blob/master/docs/setup/1-postgresql.md). Maybe a little should be added as well to help people verifying their database encoding and explaining how to adjust it.

**Comment by jjavierweb** [comment]
I have requested a pull with the documentation fix for this based on the comment of mngan

**Comment by jjavierweb** [comment]
#248
