### ISSUE TITLE
grab_prefixes returns "TypeError: '>' not supported between instances of 'int' and 'NoneType'"

### ISSUE THREAD

**Issue by smaxx1337** [respawner/peering-manager#264]
### Environment
* Python version:   3.6.8
* Peering Manager version:   master

### Steps to Reproduce
1. Go to your peering-manager directory in the CLI.
2. Run **python3.6 manage.py grab_prefixes**.

### Expected Behavior
Prefixes should be grabbed and cached.

### Observed Behavior
I receive following traceback:
```
[root@peering-manager]# python3.6 manage.py grab_prefixes -v 3
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python3.6/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python3.6/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/opt/peering-manager/peering/management/commands/grab_prefixes.py", line 26, in handle
    if len(prefixes["ipv6"]) > options["limit"]:
TypeError: '>' not supported between instances of 'int' and 'NoneType'
```

However, if I use "python3.6 manage.py grab_prefixes --limit 1" just to test, I receive this traceback instead:
```
python3.6 manage.py grab_prefixes --limit 1
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python3.6/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python3.6/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/opt/peering-manager/peering/management/commands/grab_prefixes.py", line 44, in handle
    autonomous_system.save()
  File "/usr/lib/python3.6/site-packages/django/db/models/base.py", line 746, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/lib/python3.6/site-packages/django/db/models/base.py", line 795, in save_base
    update_fields=update_fields, raw=raw, using=using,
  File "/usr/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 175, in send
    for receiver in self._live_receivers(sender)
  File "/usr/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 175, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/usr/lib/python3.6/site-packages/cacheops/query.py", line 449, in _post_save
    invalidate_obj(old, using=using)
  File "/usr/lib/python3.6/site-packages/cacheops/invalidation.py", line 36, in invalidate_obj
    invalidate_dict(model, get_obj_dict(model, obj), using=using)
  File "/usr/lib/python3.6/site-packages/funcy/decorators.py", line 39, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/usr/lib/python3.6/site-packages/cacheops/transaction.py", line 63, in queue_when_in_transaction
    return call()
  File "/usr/lib/python3.6/site-packages/funcy/decorators.py", line 60, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/site-packages/funcy/decorators.py", line 39, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/usr/lib/python3.6/site-packages/cacheops/redis.py", line 17, in handle_connection_failure
    return call()
  File "/usr/lib/python3.6/site-packages/funcy/decorators.py", line 60, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/site-packages/cacheops/invalidation.py", line 26, in invalidate_dict
    json.dumps(obj_dict, default=str)
  File "/usr/lib/python3.6/site-packages/redis/client.py", line 4067, in __call__
    return client.evalsha(self.sha, len(keys), *args)
  File "/usr/lib/python3.6/site-packages/redis/client.py", line 3143, in evalsha
    return self.execute_command('EVALSHA', sha, numkeys, *keys_and_args)
  File "/usr/lib/python3.6/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/usr/lib/python3.6/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/usr/lib/python3.6/site-packages/redis/connection.py", line 747, in read_response
    raise response
redis.exceptions.ResponseError: Error running script (call to f_0605214935a9ffcd4b9e5779300302540ff08da4): @user_script:36: @user_script: 36: Unknown Redis command called from Lua script
```

**Comment by respawner** [comment]
I'm unable to reproduce this issue. Do you still have it with the latest commit?

**Comment by smaxx1337** [comment]
I have upgraded Peering Manager now to the latest commit and have the same issue. 
I also have created the peering-manager-rq.service now.

I also have a different problem now: You can not login anymore.
If you are still logged in, everything works fine. But logging in gives back 500 and following error:
```
<class 'redis.exceptions.ResponseError'>
Error running script (call to f_0605214935a9ffcd4b9e5779300302540ff08da4): @user_script:36: @user_script: 36: Unknown Redis command called from Lua script
```

The latest entries from the /var/log/redis/redis.log:

```
386:M 27 Jul 09:30:06.251 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
386:M 27 Jul 09:30:06.251 # Server started, Redis version 3.2.12
386:M 27 Jul 09:30:07.371 * DB loaded from disk: 1.120 seconds
386:M 27 Jul 09:30:07.371 * The server is now ready to accept connections on port 6379
386:M 27 Jul 09:35:07.031 * 10 changes in 300 seconds. Saving...
386:M 27 Jul 09:35:07.035 * Background saving started by pid 849
849:C 27 Jul 09:35:07.473 * DB saved on disk
849:C 27 Jul 09:35:07.476 * RDB: 0 MB of memory used by copy-on-write
386:M 27 Jul 09:35:07.536 * Background saving terminated with success
386:M 27 Jul 09:40:08.022 * 10 changes in 300 seconds. Saving...
386:M 27 Jul 09:40:08.026 * Background saving started by pid 1152
1152:C 27 Jul 09:40:08.457 * DB saved on disk
1152:C 27 Jul 09:40:08.461 * RDB: 0 MB of memory used by copy-on-write
386:M 27 Jul 09:40:08.527 * Background saving terminated with success
```

pip3 freeze | grep redis
```
redis==3.5.3
```

Also nothing about the Redis error in the peering-manager.log files.

Peering-Manager is running on CentOS 7. 

Redis is configured in the peering_manager/configuration.py like this:
```
REDIS = {
    'tasks': {
        'HOST': 'localhost',
        'PORT': 6379,
        'PASSWORD': '',
        'CACHE_DATABASE': 0,
        'DEFAULT_TIMEOUT': 300,
        'SSL': False,
    },
    'caching': {
        'HOST': 'localhost',
        'PORT': 6379,
        'PASSWORD': '',
        'CACHE_DATABASE': 1,
        'DEFAULT_TIMEOUT': 300,
        'SSL': False,
    }
}

```

CACHE_TIMEOUT is set to 900.

```
# redis-cli ping
PONG
```

Where can I also check for logs in order to get more information about this error?

**Comment by respawner** [comment]
This is weird. What version of Redis are you using?

**Comment by smaxx1337** [comment]
Redis Server:
```
# redis-server -v
Redis server v=3.2.12 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=7897e7d0e13773f
```

Redis Client:
```
# redis-cli -v
redis-cli 3.2.12
```

**Comment by respawner** [comment]
This is probably due to the Redis version you are using. The new `django-cacheops` dependency requires Redis 4.0+ to operate as expected. I've create a pull request to address this issue in the documentation.

**Comment by smaxx1337** [comment]
It works! I can log in again. I have updated redis to 6.0.6 now: https://centos.pkgs.org/7/remi-x86_64/redis-6.0.6-1.el7.remi.x86_64.rpm.html

However, grab_prefixes still has the same error when not specifying any limit:
```
 python3 manage.py grab_prefixes
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/peering-manager/venv/lib64/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/opt/peering-manager/venv/lib64/python3.6/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/peering-manager/venv/lib64/python3.6/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/peering-manager/venv/lib64/python3.6/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/opt/peering-manager/peering/management/commands/grab_prefixes.py", line 26, in handle
    if len(prefixes["ipv6"]) > options["limit"]:
TypeError: '>' not supported between instances of 'int' and 'NoneType'
```

How can I tell grab_prefixes to have no limit?
--limit 0 = skips everything
--limit 999999999999 = would work
--limit -1 = skips everything

**Comment by respawner** [comment]
If you update to commit bda5c11 and try again with the same command, how does it go?

**Comment by smaxx1337** [comment]
```
Traceback (most recent call last):
  File "/opt/peering-manager/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/peering-manager/venv/lib64/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/opt/peering-manager/venv/lib64/python3.6/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/peering-manager/venv/lib64/python3.6/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/peering-manager/venv/lib64/python3.6/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/opt/peering-manager/peering/management/commands/grab_prefixes.py", line 26, in handle
    if "limit" in options and int(options["limit"]):
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

**Comment by respawner** [comment]
Hum... what about with 59870d5?

**Comment by smaxx1337** [comment]
Yup, works now. Thank you!
