### ISSUE TITLE
Bulk Editing in BGP Group List throws value error

### ISSUE THREAD

**Issue by mngan** [respawner/peering-manager#265]
### Environment
* Python version:  3.6.9
* Peering Manager version:  master

### Steps to Reproduce
1. List sessions for a BGP Group
1. Select multiple sessions
1. Click Edit button

<img width="698" alt="Screen Shot 2020-07-02 at 10 14 36 AM" src="https://user-images.githubusercontent.com/7329593/86390880-b3025680-bc4d-11ea-8764-890f8c6c4441.png">

```
Traceback (most recent call last):
  File "/home/milton/peering-manager/venv/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 1772, in get_prep_value
    return int(value)

The above exception (invalid literal for int() with base 10: 'AS6762 Telecom Italia Sparkle') was the direct cause of the following exception:
  File "/home/milton/peering-manager/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/milton/peering-manager/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/milton/peering-manager/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/milton/peering-manager/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/milton/peering-manager/venv/lib/python3.6/site-packages/django/contrib/auth/mixins.py", line 85, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/milton/peering-manager/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/milton/peering-manager/utils/views.py", line 435, in post
    "return_url": self.get_return_url(request),
  File "/home/milton/peering-manager/venv/lib/python3.6/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/milton/peering-manager/venv/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/milton/peering-manager/venv/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/milton/peering-manager/venv/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/milton/peering-manager/venv/lib/python3.6/site-packages/django/test/utils.py", line 95, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/milton/peering-manager/venv/lib/python3.6/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/home/milton/peering-manager/venv/lib/python3.6/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/milton/peering-manager/venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/milton/peering-manager/venv/lib/python3.6/site-packages/django/test/utils.py", line 95, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/milton/peering-manager/venv/lib/python3.6/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/home/milton/peering-manager/venv/lib/python3.6/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/milton/peering-manager/venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/milton/peering-manager/venv/lib/python3.6/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/home/milton/peering-manager/venv/lib/python3.6/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/milton/peering-manager/venv/lib/python3.6/site-packages/django/template/defaulttags.py", line 161, in render
    values = self.sequence.resolve(context, ignore_failures=True)
  File "/home/milton/peering-manager/venv/lib/python3.6/site-packages/django/template/base.py", line 670, in resolve
    obj = self.var.resolve(context)
  File "/home/milton/peering-manager/venv/lib/python3.6/site-packages/django/template/base.py", line 795, in resolve
    value = self._resolve_lookup(context)
  File "/home/milton/peering-manager/venv/lib/python3.6/site-packages/django/template/base.py", line 857, in _resolve_lookup
    current = current()
  File "/home/milton/peering-manager/venv/lib/python3.6/site-packages/django/forms/forms.py", line 475, in hidden_fields
    return [field for field in self if field.is_hidden]
  File "/home/milton/peering-manager/venv/lib/python3.6/site-packages/django/forms/forms.py", line 475, in <listcomp>
    return [field for field in self if field.is_hidden]
  File "/home/milton/peering-manager/venv/lib/python3.6/site-packages/django/forms/forms.py", line 153, in __iter__
    yield self[name]
  File "/home/milton/peering-manager/venv/lib/python3.6/site-packages/django/forms/forms.py", line 168, in __getitem__
    self._bound_fields_cache[name] = field.get_bound_field(self, name)
  File "/home/milton/peering-manager/utils/forms.py", line 229, in get_bound_field
    self.queryset = filter.filter(self.queryset, data)
  File "/home/milton/peering-manager/venv/lib/python3.6/site-packages/django_filters/filters.py", line 166, in filter
    return super().filter(qs, value)
  File "/home/milton/peering-manager/venv/lib/python3.6/site-packages/django_filters/filters.py", line 145, in filter
    qs = self.get_method(qs)(**{lookup: value})
  File "/home/milton/peering-manager/venv/lib/python3.6/site-packages/django/db/models/query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/milton/peering-manager/venv/lib/python3.6/site-packages/django/db/models/query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/milton/peering-manager/venv/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1351, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/milton/peering-manager/venv/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1382, in _add_q
    check_filterable=check_filterable,
  File "/home/milton/peering-manager/venv/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1312, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/milton/peering-manager/venv/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1166, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/milton/peering-manager/venv/lib/python3.6/site-packages/django/db/models/lookups.py", line 22, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/milton/peering-manager/venv/lib/python3.6/site-packages/django/db/models/lookups.py", line 72, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/home/milton/peering-manager/venv/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 1776, in get_prep_value
    ) from e

Exception Type: ValueError at /peering-manager/direct-peering-sessions/edit/
Exception Value: Field 'id' expected a number but got 'AS6762 Telecom Italia Sparkle'.```

**Comment by mngan** [comment]
I suspect that this is due to the table user preferences. Previously the bgp_group column was suppressed, but now it isn't and is conflicting with the hidden field bgp_group which stores the slug for the bgp_group. But because the bgp_column is no longer suppressed, django is trying to filter the using the bgp_group which expects to be an ID not a slug.
