### ISSUE TITLE
Documentation for systemd not working

### ISSUE THREAD

**Issue by altf4arnold** [respawner/peering-manager#269]
Hello,

I followed the guide to install peering-manager on debian 10. My reverse proxy is working and I can test/access to peering-manager while putting one of those two lines :
```
# ./manage.py runserver 127.0.0.1:8001
```
or
```
/opt/peering-manager# ./venv/bin/gunicorn -c /opt/peering-manager/gunicorn_config.py peering_manager.wsgi
```

Both are working. However, when I use this page of the doc to create the systemd aliases https://peering-manager.readthedocs.io/en/latest/setup/3-web-server/#systemd , I'm getting those error messages on the peering-manager.service 

```
Jul 28 15:47:45 peering-manager gunicorn[1103]: [2020-07-28 15:47:45 +0200] [1103] [INFO] Starting gunicorn 20.0.4
Jul 28 15:47:45 peering-manager gunicorn[1103]: [2020-07-28 15:47:45 +0200] [1103] [INFO] Listening at: http://127.0.0.1:8001 (1103)
Jul 28 15:47:45 peering-manager gunicorn[1103]: [2020-07-28 15:47:45 +0200] [1103] [INFO] Using worker: threads
Jul 28 15:47:45 peering-manager gunicorn[1103]: [2020-07-28 15:47:45 +0200] [1106] [INFO] Booting worker with pid: 1106
Jul 28 15:47:45 peering-manager gunicorn[1103]: [2020-07-28 15:47:45 +0200] [1106] [ERROR] Exception in worker process
Jul 28 15:47:45 peering-manager gunicorn[1103]: Traceback (most recent call last):
Jul 28 15:47:45 peering-manager gunicorn[1103]:   File "/opt/peering-manager/venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
Jul 28 15:47:45 peering-manager gunicorn[1103]:     worker.init_process()
Jul 28 15:47:45 peering-manager gunicorn[1103]:   File "/opt/peering-manager/venv/lib/python3.7/site-packages/gunicorn/workers/gthread.py", line 92, in init_process
Jul 28 15:47:45 peering-manager gunicorn[1103]:     super().init_process()
Jul 28 15:47:45 peering-manager gunicorn[1103]:   File "/opt/peering-manager/venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
Jul 28 15:47:45 peering-manager gunicorn[1103]:     self.load_wsgi()
Jul 28 15:47:45 peering-manager gunicorn[1103]:   File "/opt/peering-manager/venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
Jul 28 15:47:45 peering-manager gunicorn[1103]:     self.wsgi = self.app.wsgi()
Jul 28 15:47:45 peering-manager gunicorn[1103]:   File "/opt/peering-manager/venv/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
Jul 28 15:47:45 peering-manager gunicorn[1103]:     self.callable = self.load()
Jul 28 15:47:45 peering-manager gunicorn[1103]:   File "/opt/peering-manager/venv/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
Jul 28 15:47:45 peering-manager gunicorn[1103]:     return self.load_wsgiapp()
Jul 28 15:47:45 peering-manager gunicorn[1103]:   File "/opt/peering-manager/venv/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
Jul 28 15:47:45 peering-manager gunicorn[1103]:     return util.import_app(self.app_uri)
Jul 28 15:47:45 peering-manager gunicorn[1103]:   File "/opt/peering-manager/venv/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
Jul 28 15:47:45 peering-manager gunicorn[1103]:     mod = importlib.import_module(module)
Jul 28 15:47:45 peering-manager gunicorn[1103]:   File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
Jul 28 15:47:45 peering-manager gunicorn[1103]:     return _bootstrap._gcd_import(name[level:], package, level)
Jul 28 15:47:45 peering-manager gunicorn[1103]:   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
Jul 28 15:47:45 peering-manager gunicorn[1103]:   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
Jul 28 15:47:45 peering-manager gunicorn[1103]:   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
Jul 28 15:47:45 peering-manager gunicorn[1103]:   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
Jul 28 15:47:45 peering-manager gunicorn[1103]:   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
Jul 28 15:47:45 peering-manager gunicorn[1103]:   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
Jul 28 15:47:45 peering-manager gunicorn[1103]:   File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
Jul 28 15:47:45 peering-manager gunicorn[1103]: ModuleNotFoundError: No module named 'peering-manager'
Jul 28 15:47:45 peering-manager gunicorn[1103]: [2020-07-28 15:47:45 +0200] [1106] [INFO] Worker exiting (pid: 1106)
Jul 28 15:47:45 peering-manager gunicorn[1103]: [2020-07-28 15:47:45 +0200] [1103] [INFO] Shutting down: Master
Jul 28 15:47:45 peering-manager gunicorn[1103]: [2020-07-28 15:47:45 +0200] [1103] [INFO] Reason: Worker failed to boot.
Jul 28 15:47:45 peering-manager systemd[1]: peering-manager.service: Main process exited, code=exited, status=3/NOTIMPLEMENTED
Jul 28 15:47:45 peering-manager systemd[1]: peering-manager.service: Failed with result 'exit-code'.
```

I'm suposing something like a path problem. However, I'm not finding it obvious right now.

**Comment by smaxx1337** [comment]
I see that the example /etc/systemd/system/peering-manager.service has "peering-manager.wsgi" in it, which is wrong.
So you should replace line:

`ExecStart=/opt/peering-manager/venv/bin/gunicorn --pid /var/tmp/peering-manager.pid --pythonpath /opt/peering-manager --config /opt/peering-manager/gunicorn.py peering-manager.wsgi`

with

`ExecStart=/opt/peering-manager/venv/bin/gunicorn --pid /var/tmp/peering-manager.pid --pythonpath /opt/peering-manager --config /opt/peering-manager/gunicorn.py peering_manager.wsgi`

I could make a PR to fix this typo when I am home, but please tell me first if it works.

**Comment by altf4arnold** [comment]
Hello,
I just found that issue with a friend of mine and can confirm that it's working now. I was thinking about doing the PR myself when I'm finished at work...

**Comment by altf4arnold** [comment]
It was just the - to _
