### ISSUE TITLE
Invalid model identifier: 'utils.useraction'

### ISSUE THREAD

**Issue by jlixfeld** [respawner/peering-manager#85]
### Environment
* Python version: 3.5.3
* Peering Manager version:  commit: 7e6ec86ca254ec187986cea0fd9a56dc442fade4

### Steps to Reproduce

root@peeringmanager:/opt/peering-manager.new# ./scripts/migrate-from-sqlite.sh 

### Expected Behavior

No errors.

### Observed Behavior

```
root@peeringmanager:/opt/peering-manager.new# ./scripts/migrate-from-sqlite.sh 
Please upgrade and change your configuration.py file to use PostgreSQL
Press enter when you are ready
Migrating database (python3 manage.py migrate --run-syncdb)...
Operations to perform:
  Synchronize unmigrated apps: django_filters, django_tables2, messages, staticfiles
  Apply all migrations: admin, auth, contenttypes, peering, peeringdb, sessions, utils
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
Running migrations:
  No migrations to apply.
Importing data from JSON (python3 manage.py shell < contenttype.py)...
Importing data from JSON (python3 manage.py loaddata datadump.json)...
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/apps/config.py", line 165, in get_model
    return self.models[model_name.lower()]
KeyError: 'useraction'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/serializers/python.py", line 146, in _get_model
    return apps.get_model(model_identifier)
  File "/usr/local/lib/python3.5/dist-packages/django/apps/registry.py", line 207, in get_model
    return app_config.get_model(model_name, require_ready=require_ready)
  File "/usr/local/lib/python3.5/dist-packages/django/apps/config.py", line 168, in get_model
    "App '%s' doesn't have a '%s' model." % (self.label, model_name))
LookupError: App 'utils' doesn't have a 'useraction' model.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/commands/loaddata.py", line 72, in handle
    self.loaddata(fixture_labels)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/commands/loaddata.py", line 113, in loaddata
    self.load_label(fixture_label)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/commands/loaddata.py", line 168, in load_label
    for obj in objects:
  File "/usr/local/lib/python3.5/dist-packages/django/core/serializers/json.py", line 69, in Deserializer
    yield from PythonDeserializer(objects, **options)
  File "/usr/local/lib/python3.5/dist-packages/django/core/serializers/python.py", line 91, in Deserializer
    Model = _get_model(d["model"])
  File "/usr/local/lib/python3.5/dist-packages/django/core/serializers/python.py", line 148, in _get_model
    raise base.DeserializationError("Invalid model identifier: '%s'" % model_identifier)
django.core.serializers.base.DeserializationError: Problem installing fixture '/opt/peering-manager.new/datadump.json': Invalid model identifier: 'utils.useraction'
root@peeringmanager:/opt/peering-manager.new#
```

**Comment by respawner** [comment]
Will be addressed with the fix for #83.
